[workspace]
members = [
  "kyoto",
  "specs-tests"
]
resolver = "2"

[profile.release]
opt-level = "s"
codegen-units = 1
lto = true

[profile.dev]
split-debuginfo = "unpacked"
opt-level = 0
overflow-checks = false
lto = false