name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PIPELINE_LIBRARY_PATH: ${{ github.workspace }}/.github/library

    steps:
      - name: Checkout source Git repo
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Build Kyoto
        run: make build
