name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEFAULT_PYTHON: 3.8
      PIPELINE_CONTEXT: DEV
      PIPELINE_LIBRARY_PATH: ${{ github.workspace }}/.github/library

    steps:
      - name: Checkout source Git repo
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Initialise Python Cache
        id: venv-cache
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{runner.os}}-python-venv-${{ steps.python.outputs.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{runner.os}}-python-venv-${{ steps.python.outputs.python-version }}-

      - name: Bootstrap GitHub Library
        env:
          PIPELINE_LIBRARY_PATH: ${{env.PIPELINE_LIBRARY_PATH}}
          CACHE_STATUS: ${{steps.venv-cache.outputs.cache-hit}}
        run: ${{env.PIPELINE_LIBRARY_PATH}}/bootstrap.sh

      - name: Build Kyoto
        run: make build
